/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.iktech.artifactz.gradle.plugin

import junit.framework.TestCase.assertNotNull
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test

/**
 * A simple unit test for the 'io.iktech.artifactz.gradle.plugin.greeting' plugin.
 */
class ArtifactzPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder
            .builder()
            .build()

        project.extensions.extraProperties["artifactzApiToken"] = "d47a0104-40c3-4512-bb51-0d16569da384"
        project.plugins.apply("io.iktech.artifactz")

        // Verify the result
        assertNotNull(project.tasks.findByName("publishArtifact"))
        assertNotNull(project.tasks.findByName("pushArtifact"))
    }
}
